### ISSUE TITLE
兼容ie 吗

### ISSUE THREAD

**Issue by applenele** [zhihu/griffith#104]
你好 我想问下 这个组件兼容ie吗。我们实验ie11是不行的。

**Comment by applenele** [comment]
![image](https://user-images.githubusercontent.com/5456023/62356097-e2db4280-b542-11e9-9b06-53c9fe4541a5.png)

**Comment by ambar** [comment]
我们应该是兼容 IE 11 的。上面的错误是 codesandbox 本身不兼容。
