### ISSUE TITLE
api source 不一致

### ISSUE THREAD

**Issue by unclechong** [zhihu/griffith#126]
![image](https://user-images.githubusercontent.com/18748635/81157224-5706b300-8fb9-11ea-8013-bc53c728333c.png)

实际
interface PlaySource {
  bitrate: number
  duration: number
  format: string
  height: number
  play_url: string
  size: number
  width: number
}

大佬，以哪个为准啊

**Comment by xuxiake2017** [comment]
少一个都会报错😂
