### ISSUE TITLE
指定error 参数会播放失败，error的参数作用是什么，为什么是必传，传了之后会失败，麻烦说明一下

### ISSUE THREAD

**Issue by chenjiajing23** [zhihu/griffith#127]
## Expected behavior

![image](https://user-images.githubusercontent.com/41351722/82624441-25c2ef80-9c15-11ea-9a5b-471ffb7c4ef5.png)

## Link to repl or repo (highly encouraged)

Please provide a minimal repository on GitHub.

Issues without a reproduction link are likely to stall.

## Run `npx envinfo --system --binaries --npmPackages griffith --markdown --clipboard`

Paste the results here:

```bash

```
![image](https://user-images.githubusercontent.com/41351722/82624421-1479e300-9c15-11ea-92fd-80d578f4a11e.png)

**Comment by chenjiajing23** [comment]
![image](https://user-images.githubusercontent.com/41351722/82624605-9407b200-9c15-11ea-9414-df80cc1c9906.png)

**Comment by ambar** [comment]
类型定义错误，已经修复过。
