### ISSUE TITLE
TS类型 与文档不一致

### ISSUE THREAD

**Issue by lancelot-song** [zhihu/griffith#129]
## 🐛 Bug Report

- `index.d.ts`  中的  `PlaySource`  全部是必传，而文档是可选的
- `issue`  中提到过  `autoplay` ，源码也有， 但 `index.d.ts`  没有

**Comment by waltcow** [comment]
还有顺带吐槽一句
`PlayerContainerProps` 应该导出才用的方便啊

**Comment by xiaoyuhen** [comment]
因为后期没太有精力维护 ts 文档（主要我们用不到），欢迎 PR
