### ISSUE TITLE
怎么在播放完之后触发重新播放，我这样写能捕捉到播放完成的事件但是不能触发再次播放

### ISSUE THREAD

**Issue by xzf123456** [zhihu/griffith#130]
const {dispatchAction,subscribeEvent} = this.props
    this.play=subscribeEvent(EVENTS.DOM.ENDED, () => {
      dispatchAction(ACTIONS.PLAYER.PLAY)
    })
@wayhome @ambar @lsbigboy @lixiaoyan

**Comment by xiaoyuhen** [comment]
ACTIONS.PLAYER.PLAY 未支持，参考  https://github.com/zhihu/griffith/pull/144

欢迎 PR

**Comment by showtan001** [comment]
@xiaoyuhen 现在还不支持ACTIONS.PLAYER.PLAY？

**Comment by ambar** [comment]
@xzf123456 @showtan001 已经支持，见：#186
