### ISSUE TITLE
视频资源是后端spring-boot返回的，请求需要token验证怎么弄？

### ISSUE THREAD

**Issue by 94run** [zhihu/griffith#135]
1. 最开始想用xhr原生请求构建blob对象，返回给组件，能成功，但是不支持流式预览，大视频需要等待很久。
2. 查看了mp4的流式处理，发现使用的是xhr处理请求的，但是修改node_modules中的参数没有生效。
3. 因为是xhr请求，所以使用了ajax-hook拦截添加token，但是拦截不到。

所以主要有两个问题：
1. 为啥这个xhr请求用ajax-hook拦截不到？
2. 后期会支持自定义headers么?

**Comment by ambar** [comment]
`<video />` 资源是浏览器发起的请求，你可能最多只能使用 service worker 方法拦截。
