### ISSUE TITLE
怎么设置倍速播放

### ISSUE THREAD

**Issue by exert-oneself** [zhihu/griffith#152]
## 💬 Questions and Help

- Read carefully the README of the project
- Search if your answer has already been answered in old issues

After you can submit your question and we will be happy to help you!

**Comment by xiaoyuhen** [comment]
暂时不支持，欢迎 PR

**Comment by brahmachen** [comment]
咋不支持倍速呢。。

**Comment by ambar** [comment]
#194 已支持
