### ISSUE TITLE
进入画中画时候，显示的Playing in picture-in-picture怎么设置为中文？

### ISSUE THREAD

**Issue by showtan001** [zhihu/griffith#181]
当进入画中画时候，显示的Playing in picture-in-picture怎么才可以设置成中文？

**Comment by tingyux** [comment]
const props = {
  id: "zhihu2018",
  title: "zhihu2018",
  cover: "https://zhstatic.zhihu.com/cfe/griffith/zhihu2018.jpg",
  duration,
  locale: "zh-Hans",
  sources,
  src: "https://zhstatic.zhihu.com/cfe/griffith/zhihu2018_sd.mp4"
};


#locale: "zh-Hans",

**Comment by showtan001** [comment]
<img width="1224" alt="WechatIMG120" src="https://user-images.githubusercontent.com/32892347/126868322-833dc303-0082-4a30-8dff-775a08ff602f.png">

设置了，还是英文，其他的都是中文，就这个Playing in picture-in-picture是英文

而且如果换个视频画中画后，画中画里面的视频还是以前的，处于暂停状态。
<img width="1107" alt="WechatIMG119" src="https://user-images.githubusercontent.com/32892347/126868285-ec4c8b60-a129-4ae1-9920-16f2b5436251.png">

**Comment by showtan001** [comment]
@tingyux 而且播放另外个视频上个视频也不暂停

**Comment by showtan001** [comment]
@xiaoyuhen

**Comment by showtan001** [comment]
@wangcheng

**Comment by tingyux** [comment]
我用的是standalone 模式，看了下没问题

**Comment by showtan001** [comment]
@tingyux 语言先不管了。
大兄弟，多个视频画中画永远是第一个视频和播放下个视频上个视频暂停这两个问题怎么解决？

**Comment by tingyux** [comment]
> @tingyux语言先不管了。
> 大兄弟，有很多视频画中画永远是第一个视频和播放下个视频上个视频想这问题怎么解决？

不知道呢，使用mse和hls你解决了么？

**Comment by ambar** [comment]
![image](https://user-images.githubusercontent.com/105919/129009068-ff43fa12-92fa-4068-9cdc-36d9e898e5ae.png)

@showtan001 这个提示是由系统提供了，我验证 Chrome/Safari 都是显示中文。提供一下你的浏览器环境？
