### ISSUE TITLE
关于standalone 模式

### ISSUE THREAD

**Issue by tingyux** [zhihu/griffith#182]
## 💬 Questions and Help

- Read carefully the README of the project
- Search if your answer has already been answered in old issues

After you can submit your question and we will be happy to help you!

文档中说明了`props` 的定义请看 [Griffith 的文档](../packages/griffith#readme)。
按照官方的文档在“standalone 模式”下添加对应的js并不生效
###
#js
const props = {
  cover: "https://zhstatic.zhihu.com/cfe/griffith/zhihu2018.jpg",
  locale: "zh-Hans",
};
###
官方说可以支持hls视频，但并未给出详细文档；在清晰度选项中也并不支持“ld 流畅”选项，默认音量只有50%左右，并没有看到可以修改音量的选项。

**Comment by cc963020001** [comment]
问题一堆，这么多人提问，官方也不出文档，mp4调试正常，m3u8就是不能播放

**Comment by ambar** [comment]
@tingyux 示例下有 standalone 使用，音量可以通过 `ACTIONS.PLAYER.SET_VOLUME` 调整

**Comment by ambar** [comment]
@cc963020001 见示例：https://github.com/zhihu/griffith/blob/master/example/src/HLSPage.tsx#L21

**Comment by tingyux** [comment]
> @cc963020001 见示例：https://github.com/zhihu/griffith/blob/master/example/src/HLSPage.tsx

是不是只支持fmp4封装格式呢？standalone模式下我也测试过hls播放的问题，的确存在，即便是引用hls.js也不行

**Comment by ambar** [comment]
@tingyux 这个库利用 hls.js 播放，肯定不能提供多于 hls.js 的播放能力。

**Comment by tingyux** [comment]
> @tingyux这个库利用hls.js播放，肯定不能提供多于hls.js的播放能力。

放弃了，对于小白来说门槛略有点高
