### ISSUE TITLE
Standalone模式下如何播放HLS，谁能给个实例？

### ISSUE THREAD

**Issue by cc963020001** [zhihu/griffith#192]
这是写的MP4
[实例文件下载](https://shendu.lanzoui.com/iKc3Tsisg7c)
谁给个M3U8吧的实例？

**Comment by cc963020001** [comment]
> ## 💬 Questions and Help
> 这是写的MP4
> `
> 
> <title>视频播放器</title> <script src="https://unpkg.com/griffith-standalone/dist/index.umd.min.js"></script> <style type="text/css"> html, body {width:100%;height:100%;margin:auto;overflow: hidden;} </style>
> <script type="text/javascript"> const sources = { /*hd: { play_url: 'https://zhstatic.zhihu.com/cfe/griffith/zhihu2018_hd.mp4', } ,*/ sd: { play_url: 'https://zhstatic.zhihu.com/cfe/griffith/zhihu2018_hd.mp4', }, }
> ```
> Griffith.createPlayer(document.getElementById("mydiv")).render({sources})
> </script>
> ```
> 
> ` 谁给个M3U8吧的实例？

**Comment by ambar** [comment]
传入正确的参数，可参考：https://github.com/zhihu/griffith/blob/master/example/src/HLSPage.tsx

**Comment by snowinszu** [comment]
传入了format: 'm3u8',  但还是报错：Uncaught ReferenceError: r is not defined
```
<div id="player"></div>
<script src="https://unpkg.com/griffith-standalone/dist/index.umd.min.js"></script>
<script>
    const target = document.getElementById('player')

    const sources = {
        auto: {
            format: 'm3u8',
            play_url: 'https://cph-p2p-msl.akamaized.net/hls/live/2000341/test/level_0.m3u8',
        },
    }

    // 创建播放器
    const player = Griffith.createPlayer(target)

    // 载入视频
    player.render({sources})

</script>
```
