### ISSUE TITLE
Player props 参数问题

### ISSUE THREAD

**Issue by langzilzq** [zhihu/griffith#193]
interface PlayerContainerProps {
  id?: string
  standalone?: boolean
  title?: string
  cover?: string
  duration?: number
  sources: {[key in RealQuality]?: PlaySource}
  error?: {
    message: string
  }
  onBeforePlay?: (src: string) => Promise<void>
  onEvent?: (type: string) => void
  shouldObserveResize?: boolean
  initialObjectFit?: 'fill' | 'contain' | 'cover' | 'none' | 'scale-down'
  useMSE?: boolean
  locale?: 'en' | 'ja' | 'zh-Hans' | 'zh-Hant'
  defaultQuality?: RealQuality[]
  hiddenQualityMenu?:boolean
}
看ts interface 里面和https://github.com/zhihu/griffith/blob/master/packages/griffith/README.md
详细里面 参数不一致 后面的控制参数都没有 还有就是参数可选问题

**Comment by ambar** [comment]
https://github.com/zhihu/griffith/pull/205

@langzilzq 感觉反馈，项目己迁移至 TS，以 TS 定义为准。
