### ISSUE TITLE
online demo ?

### ISSUE THREAD

**Issue by find456789** [zhihu/griffith#21]

**Comment by xiaoyuhen** [comment]
hi @find456789 

Griffith has been widely used in the web and mobile web of Zhihu. so you can find the real context on [Zhihu](https://zhuanlan.zhihu.com/p/52747025) website.

we will build a website to introduction this project later.

**Comment by wangcheng678** [comment]
Thanks for the feedback. We plan to make an online demo with GitHub Pages in the future.
