### ISSUE TITLE
Replay text

### ISSUE THREAD

**Issue by Konserwa203** [zhihu/griffith#220]
Hello, I'd like to ask you how can I change the label of replay button? It's by default in japanesse and I'd like to change it to different language (for example polish). If it's not possible english will be fine aswell I've set the "locale" prop to "en" but it's not working

![image](https://user-images.githubusercontent.com/61764341/134014222-1ed4fafe-fdc4-470d-bdda-5bd21dcb61a8.png)
![image](https://user-images.githubusercontent.com/61764341/134014357-d74dcd20-eebe-48f0-8fa2-b7461ad19a13.png)

Best regards

**Comment by xiaoyuhen** [comment]
unfortunately, We forgot to set the locale setting for the replay button.

welcome to change the code to help the package better. The code that needs to be changed is below here

https://github.com/zhihu/griffith/blob/4f6c0cddd99c322f2fab9e903231e8c31ff3d9c9/packages/griffith/src/components/Player.tsx#L654

https://github.com/zhihu/griffith/blob/ca9139ecc694a80462fed63a9c919cf4bdb91b37/packages/griffith/src/constants/locales.ts

If you want griffith to support polish language, PR is also welcome

**Comment by xiaoyuhen** [comment]
By the way, 「重新播放」 Simplified Chinese, not Japanesse

**Comment by JakubKocierz** [comment]
gościu to jest hiński 🤦

**Comment by ambar** [comment]
@Konserwa203 Fixed in v1.18.4
