### ISSUE TITLE
safari浏览器，连续点击几次进度条，会出现异常的loading状态

### ISSUE THREAD

**Issue by leevben** [zhihu/griffith#234]
## 🐛 Bug Report

在mac的safari浏览器中，播放MP4视频（其他格式并没有试过），连续滑动几次进度条（跳转到没有加载的部分），会出现loading状态，然后视频加载出来后，loading并不会结束，而且该状态下点击暂停播放都没反应。 
PS:低网速下能更好复现， 知乎生产环境也会有这个bug出现，建议快速解决。

## To Reproduce

1.使用MacBook的safari浏览器（13、14版本均可)
2.进入demo，选择MP4
3.播放，然后连续点几次进度条跳转到没有加载的部分，直到出现loading，
4.加载完成，视频正常播放，但是loading一直存在，且暂停播放键和pause事件无效。

## Expected behavior

正常结束loading状态，暂停键可用。

## Link to repl or repo (highly encouraged)

https://codesandbox.io/embed/p03wm0o80

**Comment by leevben** [comment]
我发现好像这个是safari的bug, video标签不能在正确的时候触发waiting事件，导致事件触发顺序不正常（playing=>waiting），导致不能正确改变isLoading的状态

**Comment by ambar** [comment]
看起来是的，waiting 发生不可预期（有时没有，有时顺序不对）

**Comment by leevben** [comment]
> 看起来是的，waiting 发生不可预期（有时没有，有时顺序不对）

请问当前有计划修复这个问题吗

**Comment by ambar** [comment]
@leevben v1.22.1 中修复了。
