### ISSUE TITLE
怎么 控制 暂停 和 播放 ？

### ISSUE THREAD

**Issue by pxim** [zhihu/griffith#269]
## 💬 Questions and Help

我现在自定义了一个播放，暂停按钮，想控制 视频的播放和暂停；
没看到相关api以及视频的ref

**Comment by ambar** [comment]
https://github.com/zhihu/griffith/blob/master/example/src/MP4Page.tsx#L99-L112

**Comment by pxim** [comment]
> https://github.com/zhihu/griffith/blob/master/example/src/MP4Page.tsx#L99-L112

谢谢
