### ISSUE TITLE
Player有黑边?

### ISSUE THREAD

**Issue by pxim** [zhihu/griffith#273]
## 💬 Questions and Help

griffith 播放器有黑边。
![image](https://user-images.githubusercontent.com/5111701/164645288-bf74f153-9761-45b9-b786-de09bc2917db.png)

videojs 没有黑边
![image](https://user-images.githubusercontent.com/5111701/164645453-b1187057-fa6e-4960-b652-579c49661fba.png)

**Comment by ambar** [comment]
应该是不存在的，播放器没有任何边框也阴影样式。

**Comment by ambar** [comment]
可能是这个原因？
你可以试试 hideCover 参数：
https://github.com/zhihu/griffith/pull/259/files#r821467950

**Comment by pxim** [comment]
> 可能是这个原因？ 你可以试试 hideCover 参数： https://github.com/zhihu/griffith/pull/259/files#r821467950

好的，谢谢
