### ISSUE TITLE
怎么获取视频时间长度

### ISSUE THREAD

**Issue by wowtrxqn** [zhihu/griffith#274]
## 💬 Questions and Help

- Read carefully the README of the project
- Search if your answer has already been answered in old issues

After you can submit your question and we will be happy to help you!

我想在开始播放视频前 吧视频时间长度传给我自己的hooks里去处理一些业务

**Comment by ambar** [comment]
监听这些中的任一事件：https://github.com/zhihu/griffith/blob/master/packages/griffith-message/src/constants/events.ts#L51-L75

**Comment by wowtrxqn** [comment]
> 监听这些中的任一事件：https://github.com/zhihu/griffith/blob/master/packages/griffith-message/src/constants/events.ts#L51-L75

[EVENTS.PLAY]: Listen<DOMEventParams>
  [EVENTS.PLAYING]: Listen<DOMEventParams>
  [EVENTS.PAUSE]: Listen<DOMEventParams>
  [EVENTS.ENDED]: Listen<DOMEventParams>
  [EVENTS.TIMEUPDATE]: Listen<DOMEventParams>
  [EVENTS.CANPLAY]: Listen<DOMEventParams>
  [EVENTS.ERROR]: Listen<DOMEventParams>
  [EVENTS.WAITING]: Listen<DOMEventParams>
这里的DOMEventParams 第二个参数为啥我一直取到的是undefined

messageContextRef.useEvent(EVENTS.WAITING, (currentTime, duration, error) => {
    console.log(duration)
  })

> 监听这些中的任一事件：https://github.com/zhihu/griffith/blob/master/packages/griffith-message/src/constants/events.ts#L51-L75

感谢, 解决了

**Comment by wowtrxqn** [comment]
> 监听这些中的任一事件：https://github.com/zhihu/griffith/blob/master/packages/griffith-message/src/constants/events.ts#L51-L75

感谢, 已解决
