### ISSUE TITLE
怎么实现续播（怎么设置初始的播放时间）

### ISSUE THREAD

**Issue by MrLiSong** [zhihu/griffith#287]
## 💬 Questions and Help

- Read carefully the README of the project
- Search if your answer has already been answered in old issues

After you can submit your question and we will be happy to help you!

**Comment by MrLiSong** [comment]
知道怎么用了

**Comment by rendongsc** [comment]
@MrLiSong 怎么用？谢谢！

**Comment by rendongsc** [comment]
messageContextRef.dispatchAction(ACTIONS.TIME_UPDATE,{currentTime:80})
