### ISSUE TITLE
怎样设置自动播放视频？

### ISSUE THREAD

**Issue by git-lt** [zhihu/griffith#62]
## 💬 Questions and Help

- 怎样设置自动播放视频？

**Comment by xiaoyuhen** [comment]
hi @git-lt 

自动播放暂时是不支持的，你可以先通过手动设置的方式实现。

```
var video = document.querySelector('video')
video.volume = 0
var promise = video.play();

if (promise !== undefined) {
  promise.then(_ => {
    // 自动播放开始
  })
}
```

我们会考虑后续增加该功能。

**Comment by xiaoyuhen** [comment]
hi @git-lt 

你可以在 v1.5.0  版本使用自动播放功能

see https://github.com/zhihu/griffith/blob/master/example/mp4/App.js#L36
