### ISSUE TITLE
地址是m3u8格式的

### ISSUE THREAD

**Issue by li941168803** [zhihu/griffith#88]
## 💬 Questions and Help
报这个错：
Warning: Failed prop type: The prop `id` is marked as required in `PlayerContainer`, but its value is `undefined`.
这是为什么呢

<Player sources={{cover: 'http://172.25.28.137:6011/hls/hkstv/hls.m3u8'}} />这是代码

**Comment by xiaoyuhen** [comment]
`cover` is video image cover props

see this example 
https://github.com/zhihu/griffith/blob/master/example/hls/App.js
