### ISSUE TITLE
There are a few bugs then play in a modal. 

### ISSUE THREAD

**Issue by jaggerwang** [zhihu/griffith#89]
## 🐛 Bug Report

I have a page contains a list of videos, each click on a video will open a modal to play this video. But there are a few bugs, please help me out.

### Can not destroy the player

I need to destroy the player when close the modal, otherwise it will continue play in background. And when I play the next video, the previous one should be destroyed too.

### Duration info not in one line

![image](https://user-images.githubusercontent.com/1255011/57564720-ffa02800-73e2-11e9-9650-f38b18b74e33.png)

### Does it support auto play?

I have not found auto play prop in api doc.

## To Reproduce

Here is my code. The file object is a state, it will be set when play another video. 

```javascript
        <Player
          id={`video-player-${file.id}`}
          title={file.meta.name}
          cover={file.thumbUrls.large}
          duration={0}
          sources={{
            'hd': {
              play_url: file.url,
              size: file.meta.size,
            }
          }}
          locale="zh-Hans"
        />
```

## Run `npx envinfo --system --binaries --npmPackages griffith --markdown --clipboard`

```bash
## System:
 - OS: macOS 10.14.4
 - CPU: (4) x64 Intel(R) Core(TM) i5-4258U CPU @ 2.40GHz
 - Memory: 62.91 MB / 8.00 GB
 - Shell: 5.3 - /bin/zsh
## Binaries:
 - Node: 11.2.0 - /usr/local/bin/node
 - Yarn: 1.12.3 - /usr/local/bin/yarn
 - npm: 6.9.0 - /usr/local/bin/npm
 - Watchman: 4.9.0 - /usr/local/bin/watchman
```

**Comment by xiaoyuhen** [comment]
hi @jaggerwang 

> Can not destroy the player

you can use `ReactDOM.unmountComponentAtNode(target)` to destroy the player or use some state to control the player shown.

> Duration info not in one line

Could you please give me a demo for this problem? I can't find this case when my local context.

> Does it support auto play?

No,  it does not support autoplay, but we should support it.

Will add this feature on this weekend.

**Comment by xiaoyuhen** [comment]
The v1.5.0 version is already supported autoplay feature.

please enjoy it.
