### ISSUE TITLE
xhr.setRequestHeader('Access-Control-Allow-Origin', '*') in mp4 plugin causes CORS error

### ISSUE THREAD

**Issue by easychen** [zhihu/griffith#90]
## 🐛 Bug Report

when using MSE on mp4 file  which hosted on SinaCloud, got an error:

``` 
Access to XMLHttpRequest at 'https://static.ftqq.com/resource-f392edb2f32fe3b2cb2fd58619ac798381b91602' from origin 'http://localhost:3000' has been blocked by CORS policy: Request header field access-control-allow-origin is not allowed by Access-Control-Allow-Headers in preflight response.
```

![image](https://user-images.githubusercontent.com/1294760/57609685-ef827700-75a1-11e9-9b4b-2e09078d75e5.png)

## To Reproduce

add https://static.ftqq.com/resource-f392edb2f32fe3b2cb2fd58619ac798381b91602 as source play_url , turn useMSE on , press play button and you will see the error.

comment line 51~52  on  griffith-mp4/esm/index.js , then works well .

## Expected behavior

play the video.

## Run `npx envinfo --system --binaries --npmPackages griffith --markdown --clipboard`

Paste the results here:

```bash
*** Clipboard option removed - use clipboardy or clipboard-cli directly ***


## System:
 - OS: macOS High Sierra 10.13.6
 - CPU: (4) x64 Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz
 - Memory: 85.70 MB / 10.00 GB
 - Shell: 5.3 - /bin/zsh
## Binaries:
 - Node: 9.11.2 - ~/.nvm/versions/node/v9.11.2/bin/node
 - Yarn: 1.15.2 - ~/.yarn/bin/yarn
 - npm: 5.6.0 - ~/.nvm/versions/node/v9.11.2/bin/npm
 - Watchman: 4.7.0 - /usr/local/bin/watchman

```

**Comment by xiaoyuhen** [comment]
hi @easychen 

Thanks for your report, it's an unuseful code, we already remove this.

 please use v1.5.0 version.
