### ISSUE TITLE
any plan to support wesocket livestream with h265 

### ISSUE THREAD

**Issue by erossszh** [zhihu/griffith#94]
## 🚀 Feature Proposal

A clear and concise description of what the feature is.

## Motivation

Please outline the motivation for the proposal.

## Example

Please provide an example for how this feature would be used.

## Pitch

Why does this feature belong in the griffith ecosystem?

**Comment by xiaoyuhen** [comment]
hi @erossszh 

There are no plans for the past six months. see https://github.com/zhihu/griffith/issues/55
