### ISSUE TITLE
引入griffith时报错

### ISSUE THREAD

**Issue by Kdze** [zhihu/griffith#96]
## 💬 Questions and Help

![griffith_error](https://user-images.githubusercontent.com/33314614/58525173-57b99580-81fd-11e9-85e6-16fbbf70eb62.png)

这个报错怎么解决

**Comment by ShuangRen** [comment]
同样的报错

**Comment by ambar** [comment]
更新你的开发工具（像 CRA/Next.js 之类的工具直接可以引用就是没问题的）。

我们假设你的执行环境是最新的（支持 spread），如果不是可以使用 `@babel/preset-env` 处理你的 npm 依赖。
